### ISSUE TITLE
Zbtlink ZBT-Z8102AX - 24.10.4

### ISSUE THREAD

**Issue by arekjaskulski** [immortalwrt/immortalwrt#2123]
### Describe the bug

Hi

There is a problem with this router, see the log below , 
what am I doing wrong, where to look for the problem

* Upgrading Firmware ***
*** Data: 15466496 (0xec0000) bytes at 0x440000e0 ***
mtd: partition "ubi" extends beyond the end of device "nmbm0" -- size truncated to 0x7280000
Erasing 'ubi' from 0x580000, size 0xec0000 ... OK
Writing 'ubi' from 0x440000e0 to 0x580000, size 0xec0000 ... OK
*** Firmware upgrade completed! ***
resetting ...
F0: 102B 0000
FA: 1040 0000
FA: 1040 0000 [0200]
F9: 0000 0000
V0: 0000 0000 [0001]
00: 0000 0000
BP: 2400 0041 [0000]
G0: 1190 0000
EC: 0000 0000 [1000]
T0: 0000 024B [010F]
Jump to BL
NOTICE: BL2: v2.7(release):
NOTICE: BL2: Built : 05:15:10, Sep 20 2023
NOTICE: WDT: disabled
NOTICE: EMI: Using DDR4 settings
dump toprgu registers data:
1001c000 | 00000000 0000ffe0 00000000 00000000
1001c010 | 00000fff 00000000 00f00000 00000000
1001c020 | 00000000 00000000 00000000 00000000
1001c030 | 003c0003 003c0003 00000000 00000000
1001c040 | 00000000 00000000 00000000 00000000
1001c050 | 00000000 00000000 00000000 00000000
1001c060 | 00000000 00000000 00000000 00000000
1001c070 | 00000000 00000000 00000000 00000000
1001c080 | 00000000 00000000 00000000 00000000
dump drm registers data:
1001d000 | 00000000 00000000 00000000 00000000
1001d010 | 00000000 00000000 00000000 00000000
1001d020 | 00000000 00000000 00000000 00000000
1001d030 | 00a003f1 000000ff 00100000 00000000
1001d040 | 00027e71 000200a0 00020303 000000ff
1001d050 | 00000000 00000000 00000000 00000000
1001d060 | 00000002 00000000 00000000 00000000
drm: 500 = 0xc
[DDR Reserve] ddr reserve mode not be enabled yet
DDR RESERVE Success 0
[EMI] ComboMCP not ready, using default setting
BYTE_swap:0
BYTE_swap:0
Window Sum 552, worse bit 0, min window 68
Window Sum 544, worse bit 12, min window 64
[TxChooseVref] Worse bit 3, Min win 26, Win sum 428, Final Vref 40

Window Sum 126, worse bit 7, min window 8
Window Sum 216, worse bit 10, min window 18
Window Sum 172, worse bit 3, min window 16
Window Sum 252, worse bit 10, min window 22
Window Sum 200, worse bit 3, min window 18
Window Sum 274, worse bit 10, min window 28
Window Sum 232, worse bit 3, min window 22
Window Sum 300, worse bit 10, min window 34
Window Sum 254, worse bit 3, min window 24
Window Sum 318, worse bit 10, min window 36
Window Sum 290, worse bit 2, min window 32
Window Sum 338, worse bit 10, min window 38
Window Sum 318, worse bit 2, min window 36
Window Sum 352, worse bit 10, min window 40
Window Sum 342, worse bit 2, min window 38
Window Sum 370, worse bit 10, min window 44
Window Sum 364, worse bit 2, min window 42
Window Sum 384, worse bit 10, min window 44
Window Sum 380, worse bit 2, min window 44
Window Sum 398, worse bit 10, min window 46
Window Sum 398, worse bit 2, min window 46
Window Sum 412, worse bit 10, min window 48
Window Sum 410, worse bit 2, min window 48
Window Sum 424, worse bit 10, min window 50
Window Sum 422, worse bit 4, min window 50
Window Sum 434, worse bit 10, min window 52
Window Sum 430, worse bit 1, min window 52
Window Sum 444, worse bit 10, min window 52
Window Sum 442, worse bit 4, min window 52
Window Sum 458, worse bit 12, min window 54
Window Sum 452, worse bit 0, min window 54
Window Sum 462, worse bit 10, min window 56
Window Sum 460, worse bit 4, min window 54
Window Sum 470, worse bit 10, min window 56
Window Sum 474, worse bit 0, min window 56
mtd: partition "ubi" extends beyond the end of device "nmbm0" -- size truncated to 0x7280000
ubi0: attaching mtd6
UBI: EOF marker found, PEBs from 113 will be erased
ubi0: scanning is finished
ubi0: volume 2 ("rootfs_data") re-sized from 9 to 782 LEBs
ubi0: attached mtd6 (name "ubi", size 114 MiB)
ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
ubi0: good PEBs: 916, bad PEBs: 0, corrupted PEBs: 0
ubi0: user volume: 3, internal volumes: 1, max. volumes count: 128
ubi0: max/mean erase counter: 1/0, WL threshold: 4096, image sequence number: 1761574217
ubi0: available PEBs: 0, total reserved PEBs: 916, PEBs reserved for bad PEB handling: 19
No size specified -> Using max size (5713920)
Read 5713920 bytes from volume kernel to 0000000046000000
## Loading kernel from FIT Image at 46000000 ...
Using 'config-1' configuration
Trying 'kernel-1' kernel subimage
Description: ARM64 OpenWrt Linux-6.6.110
Type: Kernel Image
Compression: lzma compressed
Data Start: 0x460000e8

Data Size: 5684845 Bytes = 5.4 MiB
Architecture: AArch64
OS: Linux
Load Address: 0x48000000
Entry Point: 0x48000000
Hash algo: crc32
Hash value: 0be1ce7f
Hash algo: sha1
Hash value: bea871ab7bc30c7db8df7cca1fda3b188e99a8af
Verifying Hash Integrity ... crc32+ sha1+ OK
## Loading fdt from FIT Image at 46000000 ...
Using 'config-1' configuration
Trying 'fdt-1' fdt subimage
Description: ARM64 OpenWrt zbtlink_zbt-z8102ax-v2 device tree blob
Type: Flat Device Tree
Compression: uncompressed
Data Start: 0x4656c0a0
Data Size: 24007 Bytes = 23.4 KiB
Architecture: AArch64
Hash algo: crc32
Hash value: 73e9763e
Hash algo: sha1
Hash value: f1d3dbd97d553a5c13934fd6f69fa2c971e0fc75
Verifying Hash Integrity ... crc32+ sha1+ OK
Booting using the fdt blob at 0x4656c0a0
Working FDT set to 4656c0a0
Uncompressing Kernel Image
Loading Device Tree to 000000007f7f2000, end 000000007f7fadc6 ... OK
Working FDT set to 7f7f2000
Starting kernel ...
[ 0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]

[ 0.000000] Linux version 6.6.110 (buildbot@buildbot.infra.immortalwrt.org) (aarch64-openwrt-linux-
musl-gcc (OpenWrt GCC 13.3.0 r33602-e717d133ed6d) 13.3.0, GNU ld (GNU Binutils) 25

[ 0.000000] Machine model: ZBT Z8102AX V2
[ 0.000000] earlycon: uart8250 at MMIO32 0x0000000011002000 (options '')
[ 0.000000] printk: bootconsole [uart8250] enabled
[ 0.000000] OF: reserved mem: 0x0000000042ff0000..0x0000000042ffffff (64 KiB) map non-reusable
ramoops@42ff0000

[ 0.000000] OF: reserved mem: 0x0000000043000000..0x000000004302ffff (192 KiB) nomap non-
reusable secmon@43000000

[ 0.000000] OF: reserved mem: 0x0000000047c80000..0x0000000047d7ffff (1024 KiB) nomap non-
reusable wmcpu-reserved@47c80000

[ 0.000000] OF: reserved mem: 0x0000000047d80000..0x0000000047dbffff (256 KiB) nomap non-
reusable wo-emi@47d80000

[ 0.000000] OF: reserved mem: 0x0000000047dc0000..0x0000000047ffffff (2304 KiB) nomap non-
reusable wo-data@47dc0000

[ 0.000000] Zone ranges:
[ 0.000000] DMA [mem 0x0000000040000000-0x000000007fffffff]
[ 0.000000] DMA32 empty
[ 0.000000] Normal empty
[ 0.000000] Movable zone start for each node
[ 0.000000] Early memory node ranges
[ 0.000000] node 0: [mem 0x0000000040000000-0x0000000042ffffff]
[ 0.000000] node 0: [mem 0x0000000043000000-0x000000004302ffff]
[ 0.000000] node 0: [mem 0x0000000043030000-0x0000000047c7ffff]

[ 0.000000] node 0: [mem 0x0000000047c80000-0x0000000047ffffff]
[ 0.000000] node 0: [mem 0x0000000048000000-0x000000007fffffff]
[ 0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000007fffffff]
[ 0.000000] psci: probing for conduit method from DT.
[ 0.000000] psci: PSCIv1.1 detected in firmware.
[ 0.000000] psci: Using standard PSCI v0.2 function IDs
[ 0.000000] psci: MIGRATE_INFO_TYPE not supported.
[ 0.000000] psci: SMC Calling Convention v1.2
[ 0.000000] percpu: Embedded 28 pages/cpu s74984 r8192 d31512 u114688
[ 0.000000] pcpu-alloc: s74984 r8192 d31512 u114688 alloc=28*4096
[ 0.000000] pcpu-alloc: [0] 0 [0] 1
[ 0.000000] Detected VIPT I-cache on CPU0
[ 0.000000] CPU features: detected: GIC system register CPU interface
[ 0.000000] CPU features: kernel page table isolation disabled by kernel configuration
[ 0.000000] alternatives: applying boot alternatives
[ 0.000000] Kernel command line: earlycon=uart8250,mmio32,0x11002000 console=ttyS0,115200n8
[ 0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[ 0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[ 0.000000] Built 1 zonelists, mobility grouping on. Total pages: 258048
[ 0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[ 0.000000] software IO TLB: SWIOTLB bounce buffer size adjusted to 1MB
[ 0.000000] software IO TLB: area num 2.
[ 0.000000] software IO TLB: mapped [mem 0x000000007fb15000-0x000000007fc15000] (1MB)
[ 0.000000] Memory: 1004092K/1048576K available (9920K kernel code, 1574K rwdata, 6824K
rodata, 512K init, 317K bss, 44484K reserved, 0K cma-reserved)
[ 0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=2, Nodes=1
[ 0.000000] rcu: Hierarchical RCU implementation.
[ 0.000000] rcu: RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=2.
[ 0.000000] Tracing variant of Tasks RCU enabled.
[ 0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[ 0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=2
[ 0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[ 0.000000] GICv3: GIC: Using split EOI/Deactivate mode
[ 0.000000] GICv3: 640 SPIs implemented
[ 0.000000] GICv3: 0 Extended SPIs implemented
[ 0.000000] Root IRQ handler: gic_handle_irq
[ 0.000000] GICv3: GICv3 features: 16 PPIs
[ 0.000000] GICv3: CPU0: found redistributor 0 region 0:0x000000000c080000
[ 0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[ 0.000000] arch_timer: cp15 timer(s) running at 13.00MHz (phys).
[ 0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x2ff89eacb,
max_idle_ns: 440795202429 ns
[ 0.000000] sched_clock: 56 bits at 13MHz, resolution 76ns, wraps every 4398046511101ns
[ 0.008313] Calibrating delay loop (skipped), value calculated using timer frequency.. 26.00 BogoMIPS
(lpj=130000)
[ 0.018726] pid_max: default: 32768 minimum: 301
[ 0.026247] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[ 0.033693] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[ 0.043775] cacheinfo: Unable to detect cache hierarchy for CPU 0
[ 0.050455] RCU Tasks Trace: Setting shift to 1 and lim to 1 rcu_task_cb_adjust=1 rcu_task_cpu_ids=2.
[ 0.059907] rcu: Hierarchical SRCU implementation.
[ 0.064719] rcu: Max phase no-delay instances is 1000.
[ 0.070533] smp: Bringing up secondary CPUs ...
[ 0.075466] Detected VIPT I-cache on CPU1
[ 0.075513] GICv3: CPU1: found redistributor 1 region 0:0x000000000c0a0000
[ 0.075544] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[ 0.075618] smp: Brought up 1 node, 2 CPUs

[ 0.097236] SMP: Total of 2 processors activated.
[ 0.101959] CPU features: detected: 32-bit EL0 Support
[ 0.107117] CPU features: detected: CRC32 instructions
[ 0.112321] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[ 0.120711] CPU: All CPU(s) started at EL2
[ 0.124833] alternatives: applying system-wide alternatives
[ 0.134354] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns:
19112604462750000 ns
[ 0.144266] futex hash table entries: 512 (order: 3, 32768 bytes, linear)
[ 0.152087] pinctrl core: initialized pinctrl subsystem
[ 0.158548] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[ 0.164860] DMA: preallocated 128 KiB GFP_KERNEL pool for atomic allocations
[ 0.172004] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[ 0.179802] DMA: preallocated 128 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[ 0.188173] thermal_sys: Registered thermal governor 'fair_share'
[ 0.188179] thermal_sys: Registered thermal governor 'bang_bang'
[ 0.194299] thermal_sys: Registered thermal governor 'step_wise'
[ 0.200341] thermal_sys: Registered thermal governor 'user_space'
[ 0.206437] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[ 0.219426] ASID allocator initialised with 65536 entries
[ 0.225844] pstore: Using crash dump compression: deflate
[ 0.231272] pstore: Registered ramoops as persistent store backend
[ 0.237492] ramoops: using 0x10000@0x42ff0000, ecc: 0

[ 0.244079] /soc/interrupt-controller@c000000: Fixed dependency cycle(s) with /soc/interrupt-
controller@c000000

[ 0.260442] Modules: 27952 pages in range for non-PLT usage
[ 0.260454] Modules: 519472 pages in range for PLT usage
[ 0.278189] cryptd: max_cpu_qlen set to 1000
[ 0.289175] SCSI subsystem initialized
[ 0.293178] libata version 3.00 loaded.
[ 0.299127] clocksource: Switched to clocksource arch_sys_counter
[ 0.308858] NET: Registered PF_INET protocol family
[ 0.313920] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[ 0.323093] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[ 0.331509] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[ 0.339300] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[ 0.347129] TCP bind hash table entries: 8192 (order: 6, 262144 bytes, linear)
[ 0.354571] TCP: Hash tables configured (established 8192 bind 8192)
[ 0.361350] MPTCP token hash table entries: 1024 (order: 2, 24576 bytes, linear)
[ 0.368906] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[ 0.375580] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[ 0.382910] NET: Registered PF_UNIX/PF_LOCAL protocol family
[ 0.388614] NET: Registered PF_XDP protocol family
[ 0.393438] PCI: CLS 0 bytes, default 64
[ 0.398896] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[ 0.410247] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[ 0.416119] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c)
2001-2006 Red Hat, Inc.
[ 0.483835] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[ 0.493050] gpio-export gpio-export: 5 gpio(s) exported
[ 0.508605] Serial: 8250/16550 driver, 16 ports, IRQ sharing enabled
[ 0.518837] printk: console [ttyS0] disabled
[ 0.543596] 11002000.serial: ttyS0 at MMIO 0x11002000 (irq = 72, base_baud = 2500000) is a
ST16650V2
[ 0.552831] printk: console [ttyS0] enabled
[ 0.552831] printk: console [ttyS0] enabled
[ 0.561195] printk: bootconsole [uart8250] disabled

[ 0.561195] printk: bootconsole [uart8250] disabled
[ 0.576013] loop: module loaded
[ 0.581523] spi-nand spi0.0: Winbond SPI NAND was found.
[ 0.586838] spi-nand spi0.0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
[ 0.621736] Signature found at block 1022 [0x07fc0000]
[ 0.626880] NMBM management region starts at block 960 [0x07800000]
[ 0.634887] First info table with writecount 0 found in block 960
[ 0.646162] Second info table with writecount 0 found in block 963
[ 0.652351] NMBM has been successfully attached
[ 0.657257] 5 fixed-partitions partitions found on MTD device spi0.0
[ 0.663626] Creating 5 MTD partitions on "spi0.0":
[ 0.668407] 0x000000000000-0x000000100000 : "bl2"
[ 0.674171] 0x000000100000-0x000000180000 : "u-boot-env"
[ 0.680266] 0x000000180000-0x000000380000 : "Factory"
[ 0.686905] 0x000000380000-0x000000580000 : "FIP"
[ 0.693191] 0x000000580000-0x0000077a0000 : "ubi"
[ 0.890961] mtk_soc_eth 15100000.ethernet: generated random MAC address 65:74:68:25:64:00
[ 0.916027] mtk_soc_eth 15100000.ethernet eth0: mediatek frame engine at 0xffffffc081d80000, irq 75
[ 0.925964] mtk_soc_eth 15100000.ethernet eth1: mediatek frame engine at 0xffffffc081d80000, irq 75
[ 0.935807] i2c_dev: i2c /dev entries driver
[ 0.941969] mtk-wdt 1001c000.watchdog: Watchdog enabled (timeout=31 sec, nowayout=0)
[ 0.984335] NET: Registered PF_INET6 protocol family
[ 0.990626] Segment Routing with IPv6
[ 0.994318] In-situ OAM (IOAM) with IPv6
[ 0.998277] NET: Registered PF_PACKET protocol family
[ 1.003356] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to
load br_netfilter if you need this.
[ 1.016715] 8021q: 802.1Q VLAN Support v1.8
[ 1.045198] phy phy-soc:usb-phy@11e10000.1: type_sw - reg 0x218, index 0
[ 1.126102] mt7530-mdio mdio-bus:1f: configuring for fixed/2500base-x link mode
[ 1.134875] mt7530-mdio mdio-bus:1f: Link is Up - 2.5Gbps/Full - flow control rx/tx
[ 1.146232] mt7530-mdio mdio-bus:1f lan1 (uninitialized): PHY [mt7530-0:00] driver [MediaTek
MT7531 PHY] (irq=79)
[ 1.169052] mt7530-mdio mdio-bus:1f lan2 (uninitialized): PHY [mt7530-0:01] driver [MediaTek
MT7531 PHY] (irq=80)
[ 1.191675] mt7530-mdio mdio-bus:1f lan3 (uninitialized): PHY [mt7530-0:02] driver [MediaTek
MT7531 PHY] (irq=81)
[ 1.214357] mt7530-mdio mdio-bus:1f lan4 (uninitialized): PHY [mt7530-0:03] driver [MediaTek
MT7531 PHY] (irq=82)
[ 1.225962] mtk_soc_eth 15100000.ethernet eth0: entered promiscuous mode
[ 1.232723] DSA: tree 0 setup
[ 1.236754] UBI: auto-attach mtd4
[ 1.240098] ubi0: default fastmap pool size: 45
[ 1.244618] ubi0: default fastmap WL pool size: 22
[ 1.249402] ubi0: attaching mtd4
[ 2.011607] ubi0: scanning is finished
[ 2.015421] ubi0 error: ubi_read_volume_table: the layout volume was not found
[ 2.022823] ubi0 error: ubi_attach_mtd_dev: failed to attach mtd4, error -22
[ 2.029925] UBI error: cannot attach mtd4
[ 2.034124] clk: Disabling unused clocks
[ 2.038817] /dev/root: Can't open blockdev
[ 2.042950] VFS: Cannot open root device "" or unknown-block(0,0): error -6
[ 2.049903] Please append a correct "root=" boot option; here are the available partitions:
[ 2.058248] 1f00 1024 mtdblock0
[ 2.058254] (driver?)
[ 2.064776] 1f01 512 mtdblock1
[ 2.064781] (driver?)

[ 2.071302] 1f02 2048 mtdblock2
[ 2.071306] (driver?)
[ 2.077822] 1f03 2048 mtdblock3
[ 2.077826] (driver?)
[ 2.084347] 1f04 116864 mtdblock4
[ 2.084351] (driver?)
[ 2.090870] List of all bdev filesystems:
[ 2.094866] ext3
[ 2.094868] ext2
[ 2.096781] ext4
[ 2.098695] squashfs
[ 2.100617] f2fs
[ 2.102878]
[ 2.106270] Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(0,0)
[ 2.114517] SMP: stopping secondary CPUs
[ 2.118428] Kernel Offset: disabled
[ 2.121902] CPU features: 0x0,00000000,00000000,1000400b
[ 2.127201] Memory Limit: none
[ 2.132503] pstore: backend (ramoops) writing error (-28)
[ 2.137892] Rebooting in 1 seconds..
F0: 102B 0000
FA: 1040 0000
FA: 1040 0000 [0200]
F9: 0000 0000
V0: 0000 0000 [0001]
00: 0000 0000
BP: 2400 0041 [0000]
G0: 1190 0000
EC: 0000 0000 [1000]
T0: 0000 024B [010F]
Jump to BL
NOTICE: BL2: v2.7(release):
NOTICE: BL2: Built : 05:15:10, Sep 20 2023
NOTICE: WDT: disabled
NOTICE: EMI: Using DDR4 settings
dump toprgu registers data:
1001c000 | 00000000 0000ffe0 00000000 00000000
1001c010 | 00000fff 00000000 00f00000 00000000
1001c020 | 00000000 00000000 00000000 00000000
1001c030 | 003c0003 003c0003 00000000 00000000
1001c040 | 00000000 00000000 00000000 00000000
1001c050 | 00000000 00000000 00000000 00000000
1001c060 | 00000000 00000000 00000000 00000000
1001c070 | 00000000 00000000 00000000 00000000
1001c080 | 00000000 00000000 00000000 00000000
dump drm registers data:
1001d000 | 00000000 00000000 00000000 00000000
1001d010 | 00000000 00000000 00000000 00000000
1001d020 | 00000000 00000000 00000000 00000000
1001d030 | 00a003f1 000000ff 00100000 00000000
1001d040 | 00027e71 000200a0 00020303 000000ff
1001d050 | 00000000 00000000 00000000 00000000
1001d060 | 00000002 00000000 00000000 00000000

drm: 500 = 0xc
[DDR Reserve] ddr reserve mode not be enabled yet
DDR RESERVE Success 0
[EMI] ComboMCP not ready, using default setting
BYTE_swap:0
BYTE_swap:0
Window Sum 548, worse bit 0, min window 68
Window Sum 544, worse bit 12, min window 64
[TxChooseVref] Worse bit 3, Min win 24, Win sum 412, Final Vref 42
Window Sum 126, worse bit 7, min window 8
Window Sum 214, worse bit 10, min window 18
Window Sum 162, worse bit 7, min window 12
Window Sum 246, worse bit 10, min window 22
Window Sum 204, worse bit 3, min window 18
Window Sum 276, worse bit 10, min window 28
Window Sum 236, worse bit 3, min window 22
Window Sum 296, worse bit 12, min window 32
Window Sum 262, worse bit 3, min window 26
Window Sum 318, worse bit 10, min window 36 +-------------------------------------+
Window Sum 286, worse bit 3, min window 30 | |
Window Sum 330, worse bit 12, min window 36 | Nie można otworzyć /dev/ttyUSB3!
|
Window Sum 312, worse bit 2, min window 34 | |
Window Sum 352, worse bit 10, min window 40 +-------------------------------------+
Window Sum 338, worse bit 2, min window 38
Window Sum 372, worse bit 10, min window 42
Window Sum 356, worse bit 2, min window 40
Window Sum 380, worse bit 10, min window 44
Window Sum 378, worse bit 2, min window 44
Window Sum 394, worse bit 10, min window 46
Window Sum 392, worse bit 2, min window 46
Window Sum 410, worse bit 10, min window 48
Window Sum 414, worse bit 2, min window 48
Window Sum 422, worse bit 11, min window 50
Window Sum 418, worse bit 2, min window 50
Window Sum 434, worse bit 10, min window 50
Window Sum 430, worse bit 2, min window 52
Window Sum 450, worse bit 10, min window 54
Window Sum 442, worse bit 4, min window 52
Window Sum 458, worse bit 12, min window 54
Window Sum 458, worse bit 4, min window 54
Window Sum 462, worse bit 10, min window 56
Window Sum 466, worse bit 2, min window 56
Window Sum 472, worse bit 10, min window 56
Window Sum 476, worse bit 0, min window 58
Window Sum 478, worse bit 10, min window 58
Window Sum 478, worse bit 1, min window 58
Window Sum 484, worse bit 10, min window 58
NOTICE: EMI: Detected DRAM size: 1024MB
NOTICE: EMI: complex R/W mem test passed
NOTICE: CPU: MT7981 (1300MHz)
NOTICE: SPI_NAND parses attributes from parameter page.
NOTICE: SPI_NAND Detected ID 0xef
NOTICE: Page size 2048, Block size 131072, size 134217728
NOTICE: Initializing NMBM ...

### ImmortalWrt version

 24.10.4 (r33602-e717d133ed6d)

### ImmortalWrt release

 24.10.4 (r33602-e717d133ed6d)

### ImmortalWrt target/subtarget

24.10.4 

### Device

Zbtlink ZBT-Z8102AX 

### Image kind

Official downloaded image

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
So is your device "ZBT Z8102AX" or "ZBT Z8102AX V2"?
If it is the former one, you flashed wrong firmware.

```
Upgrading Firmware ***
*** Data: 15466496 (0xec0000) bytes at 0x440000e0 ***
mtd: partition "ubi" extends beyond the end of device "nmbm0" -- size truncated to 0x7280000
Erasing 'ubi' from 0x580000, size 0xec0000 ... OK
Writing 'ubi' from 0x440000e0 to 0x580000, size 0xec0000 ... OK
```

Did you modify the bootloader yourself?
The ubi partition size is not match with v1 (0x4000000) and v2 (0x7220000).

**Comment by arekjaskulski** [comment]
> So is your device "ZBT Z8102AX" or "ZBT Z8102AX V2"? If it is the former one, you flashed wrong firmware.
> 
> ```
> Upgrading Firmware ***
> *** Data: 15466496 (0xec0000) bytes at 0x440000e0 ***
> mtd: partition "ubi" extends beyond the end of device "nmbm0" -- size truncated to 0x7280000
> Erasing 'ubi' from 0x580000, size 0xec0000 ... OK
> Writing 'ubi' from 0x440000e0 to 0x580000, size 0xec0000 ... OK
> ```
> 
> Did you modify the bootloader yourself? The ubi partition size is not match with v1 (0x4000000) and v2 (0x7220000).

Hey, my device is a ZBT Z8102AX V2. I flashed versions for V1 to test, and versions for V2, and I get the exact same error message.

No, I didn't modify the bootloader - I downloaded the image from https://firmware-selector.immortalwrt.org/?version=24.10.4&target=mediatek%2Ffilogic&id=zbtlink_zbt-z8102ax-v2

and it shows these errors.

Then I flashed the original zbtlink image, and it's fine.

I'd like to flash the immortal image.

**Comment by 1715173329** [comment]
Please attach the zbtlink image here, and even better, if you can dump the fip partition from your device.

I don't have this device, it's most likely a issue from upstream which sets wrong ubi partition size.

~~To verify this, flash factory.bin first from uboot, and it should "work", then flash sysupgrade.bin in the system and you should get the same error above.~~
EDIT: Looks like you already flashed factory.bin in uboot. It's reasonable that ubi volumes still cannot be recognized.

**Comment by arekjaskulski** [comment]
hey how do I do it " dump the fip partition from your device."

**Comment by arekjaskulski** [comment]
look this 

https://forums.whirlpool.net.au/archive/9xv6r2jx

**Comment by 1715173329** [comment]
run `cat /proc/mtd` it should be mtd4 or mtd5.
Now run `dd if=/dev/mtdX of=/tmp/fip.bin` and download fip.bin with scp

**Comment by arekjaskulski** [comment]
[fip.zip](https://github.com/user-attachments/files/23508927/fip.zip)

**Comment by 1715173329** [comment]
Still need zbtlink firmware

**Comment by arekjaskulski** [comment]
[Z8102AX-2SIM-NAND-MT7981-v7.6.7.2-25.0722_110312 (1).zip](https://github.com/user-attachments/files/23509132/Z8102AX-2SIM-NAND-MT7981-v7.6.7.2-25.0722_110312.1.zip)

**Comment by arekjaskulski** [comment]
[ZBT-Z8102AX-V2-GO2025-11-07-upgrade.zip](https://github.com/user-attachments/files/23509157/ZBT-Z8102AX-V2-GO2025-11-07-upgrade.zip)   
this one works fine too

**Comment by 1715173329** [comment]
```
nmbm0:1024k(bl2),512k(u-boot-env),2048k(factory),2048k(fip),524288k(ubi)
```

so they set the ubi size to 512 MiB and it clearly exceeds the size of the flash.
after that the uboot and kernel resizes it to 114.5 MiB, I have no idea why upstream set it to 114.125 MiB.

Try these images, which should work now:
factory.bin: https://files.catbox.moe/ynfeo1.bin
sysupgrade.bin: https://files.catbox.moe/on6s5x.bin

**Comment by arekjaskulski** [comment]
Hi, thanks, it actually works, but the RM520N-GL modem is still not visible, I have been using it for a while, so I think the modem is broken or something.

**Comment by 1715173329** [comment]
openwrt/openwrt#20769

**Comment by 1715173329** [comment]
> but the RM520N-GL modem is still not visible, I have been using it for a while, so I think the modem is broken or something.

Does it work with zbtlink firmware?

**Comment by arekjaskulski** [comment]
It's the RM520N-GL 5W11H85459 version for Lenovo, and I think Lenovo has blocked something because it's not showing up in ztblink.

I also have a Banana Pi RV-2, and it shows up as a USB modem there, but it doesn't boot either.

<img width="1388" height="1090" alt="Image" src="https://github.com/user-attachments/assets/8307fa99-0453-4b2f-8c45-df520fd10110" />

<img width="1400" height="1233" alt="Image" src="https://github.com/user-attachments/assets/4e1892d2-7d66-48bf-87fa-402effa4b179" />

**Comment by giorez** [comment]
is there any chanche to get support for z8102 8GB emmc? thanks
